
project_id = "unparnunixbhxizmfvmc"
[api]
enabled = true
[db]
enabled = true
[realtime]
enabled = true
[storage]
enabled = true
[edge_functions]
enabled = true
[functions.add-default-recommendations]
verify_jwt = true
