// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzvvkmyjqpjglyljlrdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6dnZrbXlqcXBqZ2x5bGpscmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzY2NDYsImV4cCI6MjA2MTUxMjY0Nn0.2KQL5C56pcDLudp1GschxpDk97RhbTRnN-QaPYEyRPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);