// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unparnunixbhxizmfvmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVucGFybnVuaXhiaHhpem1mdm1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5Mzc4NzksImV4cCI6MjA2MTUxMzg3OX0.O8rH58v6GVDvd6V_a0GPoCDbPRmFxnbUJke2EB148EI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);